### ISSUE TITLE
Linked dropdown options not appearing in edit view

### ISSUE THREAD

**Issue by sjlevens** [genny-project/alyson#26]
I cannot select a drop down from 'What are the kinds of things would the Intern do" (Editing an Intern Profile)

**Comment by adamcrow64** [comment]
I select the detailed view of an intern.
I select edit
I can access drop down menus. I  wondered if they were appearing because I had created one earlier and that the menus were till in the browser?
I logged off and cleared everything. When I logged backed into the clean client and edited an intern I still got the menu come up.
Worth getting more testing?
